### ISSUE TITLE
Error ortográfico en una aserción de respuesta en la lección LosToquesFinos_Color  

### ISSUE THREAD

**Issue by andresanies** [dhduncan/ConoceR#16]
En el ejercicio con enunciado 

`¡Vaya cambiazo!, ¿verdad? Esta versión es más llamativa, pero no es una buena práctica, así que vamos a quitar los últimos dos argumentos con los que
| cambiamos el eje Y. Lo que sí debemos introducir en el comando son las etiquetas para los ejes. En este paso debe quitar los argumentos ylim y xpd, y en su
| lugar añadir ylab='Porcentaje de encuestados' y xlab = 'Año de la encuesta'.`

La aserción de respuesta https://github.com/dhduncan/ConoceR/blob/master/LosToquesFinos_Color/lesson.yaml#L108
tiene un error ortográfico en la palabra "Porcentage" que en realidad sería "Porcentaje" como especifica la sugerencia de respuesta
https://github.com/dhduncan/ConoceR/blob/master/LosToquesFinos_Color/lesson.yaml#L111

**Comment by dhduncan** [comment]
@andresanies muchísimas gracias!  No entiendo por qué nadie me lo hubiera comentado antes. Ya se lo arreglé.
